<?php

/**
 * @file
 * Add on module for JW Player to add poster image uploaded with content type.
 * Developer: Quentin Campbell (Max Headroom) info@maxheadroom.co.za
 */
/* * *************************************************************
 * Drupal hooks
 * ************************************************************* */

/**
 * Implements hook_help().
 */
function jw_player_poster_help($path, $arg) {
  switch ($path) {
    case 'admin/help#jw_player_poster':
      $output = '';
      $output .= '<h3>' . t('JW Player poster') . '</h3>';
      $output .= '<p>' . t('TODO') . '</p>'; //QMOD add help
      return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function jw_player_poster_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'jw_player_settings_form') {
    $field_instances = field_info_instances();
    $field_nodes = $field_instances['node'];
    $fields = array();

    foreach ($field_nodes as $node) {
      foreach ($node as $key => $field) {
        $fields[$field['field_name']] = $field['field_name'];
      }
    }
    $fields = array_unique($fields);

    $form['jw_player_poster_field'] = array(
        '#type' => 'select',
        '#title' => t('Poster image field'),
        '#description' => t('Select the content field that will be used to upload a poster image for JW Player.'),
        '#default_value' => variable_get('jw_player_poster_field', ''),
        '#options' => $fields,
    );
  }
}

/* * ************************************************************************
 * Theme preprocess
 * ************************************************************************ */

/**
 * Process variables for jw_player.tpl.php. Override for template_preprocess_jw_player.
 */
function jw_player_poster_preprocess_jw_player(&$variables) {
  $node = menu_get_object($type = 'node');
  if ($node) {
    $field = variable_get('jw_player_poster_field', '');
    $image = field_get_items('node', $node, $field);
    if ($image) {
      $variables['config']['image'] = file_create_url($image[0]['uri']);
    }
  }
}